import { spawn, type ChildProcess } from "node:child_process";
import {
  accessSync,
  chmodSync,
  constants,
  mkdirSync,
  mkdtempSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, dirname, join } from "node:path";
import type { BashOperations } from "@earendil-works/pi-coding-agent";
import {
  createRuntimeCapabilities,
  deriveCapabilityEnvironment,
  revalidateRuntimeCapabilities,
} from "./capabilities.ts";
import { emptyApprovedGrants } from "./grants.ts";
import {
  FRESH_RUNTIME_PATHS,
  validateRuntimePolicy,
  validateWritableRuntimePath,
  type ProtectedRuntimePaths,
} from "./layout.ts";
import { buildMountNamespaceArgs, createMountPlan } from "./mount-plan.ts";
import { effectiveAccess, inspectPathKind } from "./policy.ts";
import type {
  ApprovedWriteGrants,
  CompiledFilesystemPolicy,
  CompiledSandboxConfig,
  RuntimeCapabilities,
} from "./types.ts";

function unique<T>(values: T[]): T[] {
  return [...new Set(values)];
}

function rootOwnedPath(path: string): boolean {
  let current = path;
  for (;;) {
    const stat = statSync(current);
    if (stat.uid !== 0 || (stat.mode & 0o022) !== 0) return false;
    const parent = dirname(current);
    if (parent === current) return true;
    current = parent;
  }
}

/** Find an executable whose file and ancestors are trusted and policy-read-only. */
export function findTrustedBwrap(policy: CompiledFilesystemPolicy): string | undefined {
  const candidates = unique([
    "/usr/bin/bwrap",
    "/bin/bwrap",
    "/usr/local/bin/bwrap",
    ...(process.env.PATH ?? "").split(delimiter).filter(Boolean).map((path) => join(path, "bwrap")),
  ]);

  for (const candidate of candidates) {
    try {
      const canonical = realpathSync(candidate);
      accessSync(canonical, constants.X_OK);
      if (!statSync(canonical).isFile() || !rootOwnedPath(canonical)) continue;
      if (effectiveAccess(canonical, policy) === "write") continue;
      return canonical;
    } catch {
      // Try the next candidate.
    }
  }
  return undefined;
}

export async function probeBwrap(executable: string): Promise<void> {
  const args = [
    "--die-with-parent", "--new-session", "--unshare-user", "--unshare-pid",
    "--cap-drop", "ALL", "--ro-bind", "/", "/",
    "--dev", FRESH_RUNTIME_PATHS[0], "--proc", FRESH_RUNTIME_PATHS[1],
    "--", "/bin/true",
  ];

  await new Promise<void>((resolve, reject) => {
    const child = spawn(executable, args, { stdio: ["ignore", "ignore", "pipe"] });
    const stderr: Buffer[] = [];
    let settled = false;
    const finish = (error?: Error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (error) reject(error); else resolve();
    };
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      finish(new Error("bubblewrap capability probe timed out"));
    }, 3000);

    child.stderr?.on("data", (data: Buffer) => {
      if (stderr.reduce((size, chunk) => size + chunk.length, 0) < 16_384) stderr.push(data);
    });
    child.on("error", (error) => finish(error));
    child.on("close", (code) => {
      if (code === 0) finish();
      else {
        const detail = Buffer.concat(stderr).toString("utf8").trim();
        finish(new Error(`bubblewrap probe exited ${code}${detail ? `: ${detail}` : ""}`));
      }
    });
  });
}

function waitForExit(child: ChildProcess): Promise<void> {
  if (child.exitCode !== null || child.signalCode !== null) return Promise.resolve();
  return new Promise((resolve) => {
    const done = () => {
      child.removeListener("close", done);
      child.removeListener("error", done);
      resolve();
    };
    child.once("close", done);
    child.once("error", done);
  });
}

export class BubblewrapRuntime {
  readonly capabilities: RuntimeCapabilities;
  readonly protectedPaths: ProtectedRuntimePaths;
  private readonly children = new Set<ChildProcess>();
  private stopped = false;
  private shutdownTask: Promise<void> | undefined;

  constructor(
    readonly executable: string,
    readonly config: CompiledSandboxConfig,
  ) {
    const resourceRoot = mkdtempSync(join(tmpdir(), "pi-bwrap-"));
    const privateTemp = join(resourceRoot, "tmp");
    const deniedFile = join(resourceRoot, "denied-file");
    const sshClientConfig = join(resourceRoot, "ssh_config");

    try {
      chmodSync(resourceRoot, 0o700);
      mkdirSync(privateTemp, { mode: 0o700 });
      writeFileSync(deniedFile, "", { mode: 0o000 });
      chmodSync(deniedFile, 0o000);
      writeFileSync(
        sshClientConfig,
        "# Deterministic system configuration generated by the Pi Bubblewrap sandbox.\nHost *\n",
        { mode: 0o600 },
      );
      chmodSync(sshClientConfig, 0o600);
      this.capabilities = createRuntimeCapabilities({
        resourceRootPath: resourceRoot,
        privateTempPath: privateTemp,
        deniedFilePath: deniedFile,
        sshClientConfigPath: sshClientConfig,
        config,
      });
      this.protectedPaths = {
        bwrapExecutable: executable,
        hostTempParent: dirname(this.capabilities.resources.root),
        resourceRoot: this.capabilities.resources.root,
        sshClientConfigDestination: this.capabilities.resources.sshClientConfigDestination,
      };

      validateRuntimePolicy(config.filesystem, this.protectedPaths);
      createMountPlan(
        { policy: config.filesystem, grants: emptyApprovedGrants(), capabilities: this.capabilities },
        inspectPathKind,
      );
    } catch (error) {
      rmSync(resourceRoot, { recursive: true, force: true });
      throw error;
    }
  }

  get tempDirectory(): string {
    return this.capabilities.privateTemp.path;
  }

  private prepareSpawn(
    command: string,
    cwd: string,
    grants: ApprovedWriteGrants,
    callEnvironment: NodeJS.ProcessEnv,
  ): { args: string[]; environment: NodeJS.ProcessEnv } {
    if (this.stopped) throw new Error("Bubblewrap runtime has shut down");
    for (const path of grants.paths) validateWritableRuntimePath(path, this.protectedPaths, "subtree");

    const plan = createMountPlan(
      { policy: this.config.filesystem, grants, capabilities: this.capabilities },
      inspectPathKind,
    );
    const args = [
      "--die-with-parent", "--new-session", "--unshare-user", "--unshare-pid",
      "--cap-drop", "ALL", ...buildMountNamespaceArgs(plan),
    ];
    if (this.config.isolateNetwork) args.push("--unshare-net");
    args.push("--chdir", cwd, "--", "bash", "-c", command);

    return {
      args,
      environment: deriveCapabilityEnvironment(this.capabilities, process.env, callEnvironment),
    };
  }

  operations(grants: ApprovedWriteGrants): BashOperations {
    return {
      exec: async (command, cwd, { onData, signal, timeout, env: callEnv }) => {
        if (signal?.aborted) throw new Error("aborted");
        if (inspectPathKind(cwd) !== "directory") throw new Error(`Working directory does not exist: ${cwd}`);
        const prepared = this.prepareSpawn(command, cwd, grants, callEnv ?? {});

        return new Promise((resolve, reject) => {
          revalidateRuntimeCapabilities(this.capabilities);
          const child = spawn(this.executable, prepared.args, {
            cwd,
            detached: true,
            env: prepared.environment,
            stdio: ["ignore", "pipe", "pipe"],
          });
          this.children.add(child);
          let timedOut = false;
          let settled = false;
          let timer: NodeJS.Timeout | undefined;

          const kill = () => {
            if (!child.pid) return;
            try { process.kill(-child.pid, "SIGKILL"); } catch { child.kill("SIGKILL"); }
          };
          const onAbort = () => kill();
          const cleanup = () => {
            if (timer) clearTimeout(timer);
            signal?.removeEventListener("abort", onAbort);
            this.children.delete(child);
          };

          if (timeout !== undefined && timeout > 0) {
            timer = setTimeout(() => { timedOut = true; kill(); }, timeout * 1000);
          }
          child.stdout?.on("data", onData);
          child.stderr?.on("data", onData);
          signal?.addEventListener("abort", onAbort, { once: true });
          if (signal?.aborted) kill();

          child.on("error", (error) => {
            if (settled) return;
            settled = true;
            cleanup();
            reject(error);
          });
          child.on("close", (code) => {
            if (settled) return;
            settled = true;
            cleanup();
            if (signal?.aborted) reject(new Error("aborted"));
            else if (timedOut) reject(new Error(`timeout:${timeout}`));
            else resolve({ exitCode: code });
          });
        });
      },
    };
  }

  shutdown(): Promise<void> {
    if (this.shutdownTask) return this.shutdownTask;
    this.stopped = true;
    this.shutdownTask = (async () => {
      const children = [...this.children];
      const exits = children.map(waitForExit);
      for (const child of children) {
        if (!child.pid) continue;
        try { process.kill(-child.pid, "SIGKILL"); } catch { child.kill("SIGKILL"); }
      }
      await Promise.all(exits);
      this.children.clear();
      rmSync(this.capabilities.resources.root, { recursive: true, force: true });
    })();
    return this.shutdownTask;
  }
}
